import nodemailer from 'nodemailer';

/**
 * Send daily log notes via Gmail SMTP
 * @param {Object} data - Email data
 * @param {string} data.projectName - Project name
 * @param {string} data.createdBy - User who created the log
 * @param {string} data.notesText - The notes content
 * @returns {Promise<void>}
 */
export async function sendDailyLogEmail({ projectName, createdBy, notesText }) {
  console.log(`📧 Sending email...`);

  // Create transporter with exact Gmail SMTP config
  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  });

  // Format date as YYYY-MM-DD
  const dateStr = new Date().toISOString().split('T')[0];

  // Email subject
  const subject = `AI Daily Log – ${projectName} – ${dateStr}`;

  // Email body (plain text)
  const text = `AI Daily Log
Project: ${projectName}
Created By: ${createdBy}
Date: ${dateStr}

─────────────────────────────────────────

${notesText}

─────────────────────────────────────────

Generated by ANDCON MyPortal AI Notes System
`;

  // Email body (HTML formatted)
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    .header { background: #1a1a1a; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    .header h1 { margin: 0; font-size: 24px; }
    .meta { background: #f5f5f5; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
    .meta-item { margin: 5px 0; }
    .meta-label { font-weight: 600; color: #666; }
    .notes { white-space: pre-wrap; background: white; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; }
    .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e0e0e0; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🏗️ AI Daily Log</h1>
  </div>

  <div class="meta">
    <div class="meta-item"><span class="meta-label">Project:</span> ${projectName}</div>
    <div class="meta-item"><span class="meta-label">Created By:</span> ${createdBy}</div>
    <div class="meta-item"><span class="meta-label">Date:</span> ${dateStr}</div>
  </div>

  <div class="notes">${notesText.replace(/\n/g, '<br>')}</div>

  <div class="footer">
    Generated by ANDCON MyPortal AI Notes System
  </div>
</body>
</html>
`;

  // Send email
  try {
    const recipients = process.env.EMAIL_TO.split(',').map(e => e.trim()).filter(Boolean);

    const info = await transporter.sendMail({
      from: `"ANDCON MyPortal" <${process.env.GMAIL_USER}>`,
      to: recipients.join(', '),
      subject: subject,
      text: text,
      html: html,
    });

    console.log(`✓ Email sent: ${info.messageId}`);
    console.log(`  Recipients: ${recipients.join(', ')}`);
  } catch (error) {
    console.error('Email send error:', error.message);
    throw new Error(`Email sending failed: ${error.message}`);
  }
}

/**
 * Verify Gmail SMTP configuration
 */
export async function verifyEmailConfig() {
  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  });

  try {
    await transporter.verify();
    return true;
  } catch (error) {
    console.error('Email config verification failed:', error.message);
    return false;
  }
}
