import ExcelJS from 'exceljs';
import path from 'path';
import fs from 'fs';

// ─────────────────────────────────────────────
// Division → Detailed SOV row mapping
// ─────────────────────────────────────────────
const DIVISION_RANGES = {
  'DIV 2':  { startRow: 12, endRow: 13 },
  'DIV 3':  { startRow: 16, endRow: 19 },
  'DIV 4':  { startRow: 21, endRow: 22 },
  'DIV 5':  { startRow: 24, endRow: 29 },
  'DIV 6':  { startRow: 31, endRow: 39 },
  'DIV 7':  { startRow: 41, endRow: 49 },
  'DIV 8':  { startRow: 51, endRow: 51 },
  'DIV 9':  { startRow: 55, endRow: 58 },
  'DIV 10': { startRow: 61, endRow: 61 },
  'DIV 11': { startRow: 63, endRow: 64 },
  'DIV 12': { startRow: 66, endRow: 67 },
  'DIV 13': { startRow: 69, endRow: 70 },
  'DIV 14': { startRow: 72, endRow: 73 },
  'DIV 21': { startRow: 75, endRow: 76 },
  'DIV 22': { startRow: 78, endRow: 79 },
  'DIV 23': { startRow: 81, endRow: 81 },
  'DIV 26': { startRow: 82, endRow: 84 },
  'DIV 27': { startRow: 86, endRow: 87 },
  'DIV 28': { startRow: 90, endRow: 90 },
  'DIV 32': { startRow: 92, endRow: 94 },
};

const TEMPLATE_PATH = path.join(process.cwd(), 'templates', 'SOV_template.xlsx');

/**
 * Generate an Excel file from project data and scope divisions.
 * Loads the SOV template from disk if available, otherwise creates a minimal workbook.
 *
 * @param {{ name, address, version, date }} project
 * @param {Array<{ division: string, items: Array<{ title, scope }> }>} divisions
 * @returns {Promise<Buffer>} xlsx file buffer
 */
export async function generateExcel(project, divisions) {
  const workbook = new ExcelJS.Workbook();

  if (fs.existsSync(TEMPLATE_PATH)) {
    await workbook.xlsx.readFile(TEMPLATE_PATH);
  } else {
    // Minimal fallback structure — replace with real template for production
    const cover = workbook.addWorksheet('COVER');
    cover.getCell('G26').value = '';
    cover.getCell('G27').value = '';
    cover.getCell('G28').value = '';
    cover.getCell('G29').value = '';

    const sov = workbook.addWorksheet('Detailed SOV');
    sov.getCell('A1').value = 'SCOPE OF WORK — Generated by ANDCON AI Estimator';
    sov.getCell('B2').value = 'Line Item Title';
    sov.getCell('E2').value = 'Scope Description';
  }

  // ── Write COVER sheet ──────────────────────────────────────
  const coverSheet = workbook.getWorksheet('COVER');
  if (coverSheet) {
    coverSheet.getCell('G26').value = project.name    || '';
    coverSheet.getCell('G27').value = project.address || '';
    coverSheet.getCell('G28').value = project.version || '';
    coverSheet.getCell('G29').value = project.date    || '';
  }

  // ── Write Detailed SOV sheet ───────────────────────────────
  const sovSheet = workbook.getWorksheet('Detailed SOV');
  if (sovSheet) {
    for (const divData of divisions) {
      const range = DIVISION_RANGES[divData.division];
      if (!range) continue;

      const capacity = range.endRow - range.startRow + 1;
      // Respect capacity — do not write beyond the reserved rows
      const items = divData.items.slice(0, capacity);

      items.forEach((item, idx) => {
        const rowNum = range.startRow + idx;
        const titleCell = sovSheet.getCell(`B${rowNum}`);
        const scopeCell = sovSheet.getCell(`E${rowNum}`);

        // Preserve existing cell style — only overwrite value
        titleCell.value = item.title  || '';
        scopeCell.value = item.scope  || '';
      });
    }
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
}
